inventory/urls.py
from django.conf.urls import url

from inventory import views

urlpatterns = [
    url(r'^items/$', views.ItemList.as_view(), name='item-list'),
    url(r'^$', views.ItemListView.as_view(), name='items'),
    url(r'^item-create/$', views.ItemCreateView.as_view(), name='item-create'),
    url(r'^item/(?P<pk>\d+)/update/$', views.ItemUpdateView.as_view(), name='item-update'),
    url(r'^item/(?P<pk>\d+)/$', views.ItemDetailView.as_view(), name='item-detail'),
    url(r'^item-delete/(?P<pk>\d+)/$', views.ItemConfirmDeleteView.as_view(), name='item-delete'),
]

inventory_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('inventory.urls', namespace='inventory')),
]

inventory/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.


class Vendor(models.Model):
    name = models.CharField(max_length=64)
    url = models.CharField(max_length=64, blank=True, null=True)
    lookup_url = models.CharField(max_length=128, blank=True, null=True,
                                  help_text="url pattern to look up catalog number")
    phone = models.CharField(max_length=16, blank=True, null=True)
    rep = models.CharField(max_length=45, blank=True, null=True)
    rep_phone = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']



class Category(models.Model):
    name = models.CharField(max_length=45)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['name']

class Item(models.Model):
    name = models.CharField(max_length=128)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT)
    catalog = models.CharField('Catalog number', max_length=45,
                               blank=True, null=True)
    size = models.DecimalField('Size of unit',
                               max_digits=10, decimal_places=2,
                               blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    date_added = models.DateField(auto_now_add=True)
    comments = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def vendor_url(self):
        try:
            return self.vendor.lookup_url % self.catalog
        except (AttributeError, TypeError):
            return None

    def get_absolute_url(self):
        return reverse("inventory:item-detail", kwargs={'pk': self.pk})

inventory/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from inventory.models import Item
from django.urls import reverse_lazy
from serializers import (
    ItemSerializer)
from rest_framework import generics
import urllib
import requests

class ItemListView(generic.ListView):
    template_name = 'inventory/item.html'
    context_object_name = 'item_list'

    def get_queryset(self):
        if 'all_user' in self.request.GET:
            urlencode = urllib.urlencode(self.request.GET)
            item_list = requests.get('http://mng-inventory-management.herokuapp.com/items/?'+urlencode).json()
            item_ids = []
            for item in item_list:
                item_ids.append(item['id'])

            return Item.objects.filter(id__in=item_ids)
        return Item.objects.filter(is_active=True).order_by('-date_added')

    def get_context_data(self, **kwargs):
        context = super(ItemListView, self).get_context_data(**kwargs)
        if self.request.GET.get('all_user', None):
            context['all_user'] = True
            context['active_user'] = False
        if self.request.GET.get('active_user', None):
            context['active_user'] = True
            context['all_user'] = False

        return context

class ItemCreateView(CreateView):
    model = Item
    fields = ['name', 'vendor', 'catalog', 'size', 'category']
    success_url = reverse_lazy('inventory:items')


class ItemUpdateView(UpdateView):
    model = Item
    fields = ['name', 'vendor', 'catalog', 'size', 'category']
    success_url = reverse_lazy('inventory:items')
    template_name_suffix = '_update_form'


class ItemDetailView(generic.DetailView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        context['lineitems'] = context['item']
        return context


class ItemConfirmDeleteView(generic.DeleteView):
    template_name = 'inventory/confirm_delete_items.html'
    model = Item
    success_url = reverse_lazy('inventory:items')
    items_to_delete = []

    def get_context_data(self, **kwargs):
        context = super(ItemConfirmDeleteView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):

        # self.items_to_delete = self.request.POST.getlist('itemsToDelete')
        if self.request.POST.get("confirm_delete"):
            # when confirmation page has been displayed and confirm button
            # pressed
            item_to_delete = self.get_queryset().get(id=self.kwargs['pk'])
            item_to_delete.is_active = False
            item_to_delete.save()
            return HttpResponseRedirect(self.success_url)
        elif self.request.POST.get("cancel"):
            # when confirmation page has been displayed and cancel button
            # pressed
            return HttpResponseRedirect(self.success_url)
        else:
            # when data is coming from the form which lists all items
            return self.get(self, *args, **kwargs)

class ItemList(generics.ListAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer

    def get_queryset(self):
        if 'all_user' in self.request.GET:
            return self.queryset.all()
        else:
            return self.queryset.filter(is_active=True)

templates/inventory/confirm_delete_items.html
{% load i18n %}
<form action="" method="post">
    {% csrf_token %}
    {% trans 'The following objects as well as their related objects will be deleted. Are you sure?' %}
    <ul>
        <input type="hidden" value="{{ item.id }}" name="itemsToDelete" />
        <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
    </ul>
    <input type="submit" class="btn btn-primary" value="{% trans 'Confirm deletion' %}" name="confirm_delete" />
    <input type="submit" class="btn btn-primary" value="{% trans 'Cancel' %}" name="cancel"/>
</form>

templates/inventory/item_detail.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Item Name</th>
      <th>Vendor</th>
      <th>Catalog</th>
      <th>Size</th>
      <th>Category</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
		    <tr>
		      <th scope="row">1</th>
		      <td>{{ lineitems.name }}</td>
		      <td>{{ lineitems.vendor }}</td>
		      <td>{{ lineitems.catalog }}</td>
		      <td>{{ lineitems.size }}</td>
		      <td>{{ lineitems.category }}</td>
		      <td>{{ lineitems.date_added }}</td>
		    </tr>
  </tbody>
</table>

<a href="{% url 'inventory:items' %}" type="button" class="btn-primary" >Cancel</a>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

templates/inventory/item_form.html
<form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

templates/inventory/item_list.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<div class="col-md-3">
  <div class="row">
      <form action="{% url 'inventory:items' %}" method="get">
        <label>Active Items</label>
        <input type="radio" id="active_user" name="active_user" value="Active Users" onChange='this.form.submit();' {% if active_user %} checked="true" {% endif %}/>
      </form>
      <form action="{% url 'inventory:items' %}" method="get">
        <label>All Items</label>
        <input type="radio" id="all_user" name="all_user" {% if all_user %} checked="true" {% endif %} value="All Users"  onChange='this.form.submit();'/>
      </form>
    </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Item Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    	{% for item in item_list %}
		    <tr>
		      <th scope="row">{{forloop.counter}}</th>
		      <td>{{ item.name }}</td>
		      <td> <a href="{% url 'inventory:item-update' item.id %}"> Edit </a></td>
		      <td> <a href="{% url 'inventory:item-delete' item.id %}"> Delete </a></td>
		      <td> <a href="{% url 'inventory:item-detail' item.id %}"> View </a></td>
		    </tr>
    	{% endfor %}
  </tbody>
</table>

<a href="{% url 'inventory:item-create' %}" type="button" class="btn-primary"> Create New Item</a>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'>
</script>

templates/inventory/item_update_form.html
<form action="" method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>